# Generated by Django 6.0.2 on 2026-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_early_bird',
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.CharField(choices=[('neat', 'Very Neat/Organized'), ('average', 'Average'), ('relaxed', 'Relaxed/Messy')], default='average', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, help_text='List a few things you love'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, help_text='Home Region/District', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_habit',
            field=models.CharField(choices=[('quiet', 'Quiet'), ('group', 'Group')], max_length=10),
        ),
    ]
