# Generated by Django 6.0.2 on 2026-03-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_is_early_bird_profile_cleanliness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_early_bird',
            field=models.BooleanField(default=True),
        ),
    ]
