# Generated by Django 6.0.2 on 2026-03-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_early_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='smoking_habit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_weight',
            field=models.IntegerField(default=1),
        ),
    ]
