# Generated by Django 6.0.2 on 2026-03-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_smoking_habit_profile_smoking_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='smoking_habit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_weight',
            field=models.IntegerField(default=0),
        ),
    ]
