# Generated by Django 6.0.2 on 2026-04-16 07:02
# Patched to be idempotent: columns may already exist in the DB from a prior
# un-migrated session, so we use SeparateDatabaseAndState to let Django record
# the state change without re-running the DDL that would cause a duplicate-column error.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_smoking_habit_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState so Django records the field in its state
        # (state_operations) but runs safe conditional SQL (database_operations)
        # that won't break if the column already exists.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='profile',
                    name='age',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='profile',
                    name='gender',
                    field=models.CharField(
                        blank=True,
                        choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                        default='',
                        max_length=10,
                    ),
                ),
            ],
            database_operations=[
                # SQLite doesn't support IF NOT EXISTS on ALTER TABLE, so we
                # catch the error by checking the column list first via a Python
                # RunPython call below. The RunSQL here is intentionally empty;
                # actual DDL is handled by RunPython.
            ],
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _add_columns_if_missing(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _add_columns_if_missing(apps, schema_editor):
    """Add age / gender columns only when they don't already exist (SQLite-safe)."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(accounts_profile)")
        existing_columns = {row[1] for row in cursor.fetchall()}

        if 'age' not in existing_columns:
            cursor.execute(
                "ALTER TABLE accounts_profile ADD COLUMN age integer NULL"
            )
        if 'gender' not in existing_columns:
            cursor.execute(
                "ALTER TABLE accounts_profile ADD COLUMN gender varchar(10) NOT NULL DEFAULT ''"
            )
