# Generated by Django 6.0.2 on 2026-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sync_habits_and_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cleanliness_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinking_habit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinking_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_habit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion_habit',
            field=models.CharField(choices=[('quietly', 'Quietly (Personal/Silent)'), ('loud', 'Loud (Speaking/Chanting)'), ('vocal', 'Vocal (Singing/Community)')], default='quietly', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='visitors_habit',
            field=models.IntegerField(default=0),
        ),
    ]
