# Generated by Django 6.0.2 on 2026-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fix_religion_habit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, default='student', max_length=50),
        ),
    ]
