# Generated by Django 6.0.2 on 2026-04-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mass_sync_ghost_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cleanliness_habit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_preference_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noise_tolerance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noise_tolerance_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_hostel_area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reading_habit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reading_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sharing_habit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sharing_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleep_schedule',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleep_schedule_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleeptime_habit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sleeptime_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='smoking_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_activity_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='study_habit_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visitors_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_of_study',
        ),
    ]
