# Generated by Django 6.0.2 on 2026-02-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('disc', models.TextField()),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='images/')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
