# Generated by Django 6.0.2 on 2026-02-19 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_from_campus', models.IntegerField(help_text='Distance in meters')),
                ('gender_type', models.CharField(choices=[('M', 'Male Only'), ('F', 'Female Only'), ('X', 'Mixed')], max_length=1)),
                ('is_self_contained', models.BooleanField(default=True)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('main_photo', models.ImageField(upload_to='hostels/')),
                ('is_quiet_environment', models.BooleanField(default=True)),
                ('has_reading_room', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
