# Generated by Django 6.0.2 on 2026-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
