# Generated by Django 6.0.2 on 2026-02-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_hostel_has_wifi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='is_quiet_environment',
        ),
    ]
