# Generated by Django 6.0.2 on 2026-02-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_remove_hostel_is_quiet_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_quiet_environment',
            field=models.BooleanField(default=True),
        ),
    ]
