# Generated by Django 6.0.2 on 2026-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_hostel_is_quiet_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
