# Generated by Django 6.0.2 on 2026-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_alter_hostel_available_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='bath_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/bath_photos/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='compound_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/compound_photos/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='room_phto',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/room_photos/'),
        ),
    ]
