# Generated by Django 6.0.2 on 2026-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_hostel_bath_photo_hostel_compound_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='manager_phone',
            field=models.CharField(default='0777....', help_text='Contact for bookings', max_length=15),
            preserve_default=False,
        ),
    ]
