# Generated by Django 6.0.2 on 2026-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0009_roommateproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='wants_roommate',
            field=models.BooleanField(default=False, help_text='Only relevant for double rooms'),
        ),
    ]
