# Generated by Django 6.0.2 on 2026-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0010_booking_room_type_booking_wants_roommate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
