# Generated by Django 6.0.2 on 2026-04-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0010_booking_room_type_booking_wants_roommate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='room_phto',
            new_name='room_photo',
        ),
    ]
