# Generated by Django 6.0.2 on 2026-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_hostel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
